# Generated by Django 4.2.1 on 2023-06-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chat_receiver_remove_chat_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
