# Generated by Django 4.2.1 on 2023-06-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chat_receiver_chat_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sender',
        ),
    ]
